# Generated by Django 5.1.3 on 2024-11-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idAdocao", models.IntegerField()),
                ("adocao", models.CharField(max_length=50)),
                ("dt_adocao", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idAnimal", models.IntegerField()),
                ("idade", models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idEspecie", models.IntegerField()),
                ("especie", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Faixa_Salarial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idFaixa_salarial", models.IntegerField()),
                ("faixa_salarial", models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idGenero", models.IntegerField()),
                ("genero", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idMonitor", models.IntegerField()),
                ("monitor", models.CharField(max_length=30)),
                ("dt_nasc", models.DateField()),
                ("telefone", models.CharField(max_length=11)),
                ("email", models.CharField(max_length=20)),
                ("sexo", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("Nome", models.CharField(max_length=50)),
                ("dt_nasc", models.DateField()),
                ("idade", models.IntegerField()),
                ("endereco", models.CharField(max_length=99)),
                ("telefone", models.CharField(max_length=11)),
                ("senha", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Porte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idPorte", models.IntegerField()),
                ("porte", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Raca_cachorro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idRaca_cachorro", models.IntegerField()),
                ("raca", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Raca_gato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idRaca_gato", models.IntegerField()),
                ("raca", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idSexo", models.IntegerField()),
                ("sexo", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Status_Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idStatus", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Status_visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idStatus_visista", models.IntegerField()),
                ("status_visita", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idVisita", models.IntegerField()),
                ("dt_visita", models.DateField()),
                ("hr_visita", models.TimeField()),
            ],
        ),
    ]
