# Generated by Django 5.2 on 2025-05-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('roedor', 'Roedor'), ('reptil', 'Réptil'), ('peixe', 'Peixe'), ('outros', 'Outros')], max_length=100, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande'), ('gigante', 'Gigante')], max_length=100, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea'), ('nao_informado', 'Não Informado')], max_length=100, verbose_name='Sexo'),
        ),
    ]
