# Generated by Django 5.2 on 2025-05-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0002_alter_animal_options_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='disponivel_adocao',
            field=models.BooleanField(default=False, verbose_name='Disponível para Adoção?'),
        ),
    ]
