# Generated by Django 5.2 on 2025-05-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0003_animal_disponivel_adocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_visita', models.DateField(verbose_name='Data da Visita')),
                ('hora_visita', models.TimeField(verbose_name='Hora da Visita')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendente', max_length=20, verbose_name='Status da Visita')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='MyPet.animal', verbose_name='Animal a ser visitado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_solicitadas', to='MyPet.perfil', verbose_name='Solicitante da Visita')),
            ],
            options={
                'verbose_name': 'Visita de Acompanhamento',
                'verbose_name_plural': 'Visitas de Acompanhamento',
                'ordering': ['data_visita', 'hora_visita'],
            },
        ),
    ]
