# Generated by Django 5.2 on 2025-05-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0004_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não Binário'), ('outro', 'Outro'), ('prefiro_nao_dizer', 'Prefiro não dizer')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_residencia',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('condominio', 'Condomínio'), ('sitio_fazenda', 'Sítio / Fazenda'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Residência'),
        ),
    ]
