# Generated by Django 5.2 on 2025-05-26 22:59

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0005_alter_perfil_genero_alter_perfil_tipo_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='perfis', variations={'thumb': (128, 128, True)}, verbose_name='Foto de Perfil'),
        ),
    ]
