# Generated by Django 5.2 on 2025-05-27 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0006_perfil_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conversa Ativa?')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPet.animal', verbose_name='Animal Referência')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_recebidas', to='MyPet.perfil', verbose_name='Dono do Animal')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_iniciadas', to='MyPet.perfil', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Conversa de Adoção',
                'verbose_name_plural': 'Conversas de Adoção',
                'ordering': ['-modificado'],
                'unique_together': {('solicitante', 'dono', 'animal')},
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='MyPet.conversa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPet.perfil')),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
