# Generated by Django 5.2 on 2025-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0008_mensagem_campo_temporario_para_migracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
