# Generated by Django 5.2 on 2025-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0009_alter_animal_criado_alter_animal_modificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
