# Generated by Django 5.2 on 2025-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0010_mensagem_media_file_mensagem_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='descricao_necessidades',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição das Necessidades Especiais'),
        ),
        migrations.AddField(
            model_name='animal',
            name='necessidade_espaco',
            field=models.CharField(choices=[('pequeno', 'Pouco (apartamento)'), ('medio', 'Médio (casa sem quintal grande)'), ('grande', 'Grande (casa com quintal)')], default='medio', max_length=50, verbose_name='Necessidade de Espaço'),
        ),
        migrations.AddField(
            model_name='animal',
            name='necessidades_especiais',
            field=models.BooleanField(default=False, verbose_name='Possui Necessidades Especiais?'),
        ),
        migrations.AddField(
            model_name='animal',
            name='nivel_energia',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=50, verbose_name='Nível de Energia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='socializacao_criancas',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('depende', 'Depende'), ('nao_avaliado', 'Não Avaliado/Informado')], default='nao_avaliado', max_length=50, verbose_name='Socialização com Crianças'),
        ),
        migrations.AddField(
            model_name='animal',
            name='socializacao_outros_animais',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('depende', 'Depende'), ('nao_avaliado', 'Não Avaliado/Informado')], default='nao_avaliado', max_length=50, verbose_name='Socialização com Outros Animais'),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperamento',
            field=models.CharField(default='desconhecido', help_text='Ex: Calmo, brincalhão, tímido, independente, sociável.', max_length=100, verbose_name='Temperamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='disposicao_necessidades_especiais',
            field=models.BooleanField(default=False, verbose_name='Disposto(a) a Adotar Animal com Necessidades Especiais?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencia_animais',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma'), ('alguma', 'Alguma'), ('muita', 'Muita')], default='alguma', max_length=50, verbose_name='Experiência Prévia com Animais'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idades_criancas',
            field=models.CharField(blank=True, help_text='Ex: 0-5, 6-12, 13+ ou "Não se aplica"', max_length=100, null=True, verbose_name='Faixa Etária das Crianças (se houver)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_atividade_usuario',
            field=models.CharField(choices=[('baixo', 'Calmo/Sedentário'), ('medio', 'Moderado'), ('alto', 'Muito Ativo')], default='medio', max_length=50, verbose_name='Seu Nível de Atividade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencia_especie_animal',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('roedor', 'Roedor'), ('reptil', 'Réptil'), ('peixe', 'Peixe'), ('outros', 'Outros'), ('qualquer', 'Qualquer Espécie')], default='qualquer', max_length=100, verbose_name='Espécie Preferencial'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencia_idade_animal',
            field=models.CharField(choices=[('filhote', 'Filhote'), ('adulto', 'Adulto'), ('idoso', 'Idoso'), ('qualquer', 'Qualquer Idade')], default='qualquer', max_length=50, verbose_name='Idade Preferencial do Animal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencia_porte_animal',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande'), ('gigante', 'Gigante'), ('qualquer', 'Qualquer Porte')], default='qualquer', max_length=50, verbose_name='Porte Preferencial do Animal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tem_criancas',
            field=models.BooleanField(default=False, verbose_name='Possui Crianças em Casa?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tem_outros_animais',
            field=models.BooleanField(default=False, verbose_name='Possui Outros Animais de Estimação?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='temperamento_outros_animais',
            field=models.CharField(blank=True, choices=[('docil', 'Dócil'), ('dominante', 'Dominante'), ('brincalhao', 'Brincalhão'), ('nao_se_aplica', 'Não se Aplica')], max_length=100, null=True, verbose_name='Temperamento dos Outros Animais (se houver)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_outros_animais',
            field=models.CharField(blank=True, choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outros', 'Outros'), ('nao_possui', 'Não Possui')], max_length=100, null=True, verbose_name='Tipo de Outros Animais (se houver)'),
        ),
    ]
