# Generated by Django 5.2 on 2025-06-02 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0011_animal_descricao_necessidades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['criado'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='data_envio',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagem',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('other', 'Outro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='MyPet.perfil'),
        ),
        migrations.CreateModel(
            name='CompatibilidadeGemini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação de Compatibilidade')),
                ('explicacao', models.TextField(blank=True, null=True, verbose_name='Explicação da Compatibilidade')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_gemini', to='MyPet.animal')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_gemini', to='MyPet.perfil')),
            ],
            options={
                'verbose_name': 'Compatibilidade Gemini',
                'verbose_name_plural': 'Compatibilidades Gemini',
                'unique_together': {('perfil', 'animal')},
            },
        ),
    ]
