# Generated by Django 5.2 on 2025-06-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPet', '0012_alter_mensagem_options_remove_mensagem_data_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='temperamento',
            field=models.CharField(choices=[('calmo', 'Calmo'), ('brincalhao', 'Brincalhão'), ('timido', 'Tímido'), ('independente', 'Independente'), ('sociável_humanos', 'Sociável com Humanos'), ('sociável_animais', 'Sociável com Outros Animais'), ('agitado', 'Agitado'), ('ansioso_separacao', 'Ansiedade de Separação'), ('vocal', 'Vocal (Late/Mia Muito)'), ('destrutivo', 'Destrutivo'), ('ciumento', 'Ciumento'), ('protetor', 'Protetor'), ('medroso', 'Medroso'), ('reservado', 'Reservado'), ('adaptavel', 'Adaptável'), ('necessita_lideranca', 'Necessita Liderança/Experiência'), ('agressivo_animais', 'Agressivo com Outros Animais'), ('agressivo_humanos', 'Agressivo com Humanos'), ('agressivo_estranhos', 'Agressivo com Estranhos'), ('reativo', 'Reativo (a estímulos)'), ('nao_avaliado', 'Não Avaliado/Informado'), ('desconhecido', 'Desconhecido')], help_text='Selecione os temperamentos que melhor descrevem o animal (múltiplas escolhas)', max_length=255, verbose_name='Temperamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idades_criancas',
            field=models.CharField(blank=True, choices=[('0_2', '0-2 anos (Bebês/Crianças de colo)'), ('3_5', '3-5 anos (Crianças pequenas)'), ('6_12', '6-12 anos (Crianças em idade escolar)'), ('13_17', '13-17 anos (Adolescentes)'), ('nao_se_aplica', 'Não se Aplica (Não possui crianças)')], help_text='Selecione as faixas etárias das crianças em casa (múltiplas escolhas, ex: 0-2 anos, 6-12 anos)', max_length=255, null=True, verbose_name='Faixa Etária das Crianças (se houver)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='temperamento_outros_animais',
            field=models.CharField(blank=True, choices=[('docil', 'Dócil'), ('dominante', 'Dominante'), ('brincalhao', 'Brincalhão'), ('competitivo', 'Competitivo'), ('reservado', 'Reservado'), ('ansioso', 'Ansioso'), ('reativo', 'Reativo'), ('nao_se_aplica', 'Não se Aplica (se não houver animais)'), ('nao_avaliado', 'Não Avaliado/Informado')], help_text='Selecione os temperamentos dos outros animais (múltiplas escolhas)', max_length=255, null=True, verbose_name='Temperamento dos Outros Animais (se houver)'),
        ),
    ]
