"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv # Importa config e Csv de decouple
import os # Necessário para os.path.join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Debug true pra dev; debug false pra prod
DEBUG = config("DEBUG", cast=bool, default=True)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MyPet',
    'bootstrap4',
    'stdimage',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'MyPet', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bancopet',
        'USER': 'root',
        'PASSWORD': 'P3TL3P3TR3P3T',
        'HOST': 'localhost',
        'PORT': '3306',
    }

}


# Password validation
# https://docs.djangoproject.com/en/5.1/topics/password-validation/

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/topics/static-files/

STATIC_URL = 'static/' # Usado durante dev
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Usado durante prod

# Media Files (user-uploaded files)
MEDIA_URL = '/media/' # URL para servir arquivos de mídia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Diretório onde os arquivos de mídia serão armazenados

# --- CONFIGURAÇÕES DE EMAIL ---
# Para desenvolvimento, use o backend de console (imprime no terminal)
# Em produção, você deverá configurar um servidor SMTP real.
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST')
    EMAIL_PORT = config('EMAIL_PORT', cast=int)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=False)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool, default=False) # Geralmente False se EMAIL_USE_TLS for True
    SERVER_EMAIL = config('SERVER_EMAIL', default=EMAIL_HOST_USER) # Email para o qual erros são enviados

# Email padrão que será usado como remetente nas suas notificações
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')
# --- FIM DAS CONFIGURAÇÕES DE EMAIL ---


# IMPORTANTE: A URL para onde o Django redireciona após um login bem-sucedido
LOGIN_REDIRECT_URL = 'telaprincipal'

# A URL para onde o Django redireciona após o logout
LOGOUT_REDIRECT_URL = 'index' # Redireciona para a página de login (index) após o logout

# A URL para onde o Django redireciona usuários não autenticados que tentam acessar
# uma view protegida por @login_required (por padrão é '/accounts/login/')
LOGIN_URL = 'index' # Faz com que a raiz (index.html) seja a página de login

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURAÇÃO DA API DO GEMINI ---
GEMINI_API_KEY = config('GOOGLE_API_KEY') # Carrega a chave da API do Gemini do .env
# --- FIM DA CONFIGURAÇÃO DA API DO GEMINI ---